# Generated by Django 4.2.16 on 2024-12-03 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('contrasenia', models.CharField(max_length=128)),
                ('acerca', models.CharField(max_length=400)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('ncontacto', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'artista',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(max_length=200)),
                ('artista', models.ForeignKey(blank=True, db_column='artista', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.artista')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=255)),
                ('imagen', models.ImageField(upload_to='obras/')),
                ('artista', models.ForeignKey(blank=True, db_column='artista', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.artista')),
            ],
            options={
                'db_table': 'obra',
            },
        ),
    ]
