# Generated by Django 4.2.16 on 2024-12-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='imagen',
            field=models.ImageField(default='No proporcionado', upload_to='artistas/'),
            preserve_default=False,
        ),
    ]
