# Generated by Django 4.2.16 on 2025-01-11 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_producto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('artista', models.ForeignKey(db_column='artista', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='app.artista')),
            ],
            options={
                'db_table': 'evento',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
