# Generated by Django 4.2.16 on 2025-01-13 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_evento_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipacionEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('RECHAZADO', 'Rechazado'), ('PARTICIPANDO', 'Participando'), ('EN_ESPERA', 'En Espera')], default='EN_ESPERA', max_length=20)),
                ('solicitado_en', models.DateTimeField(auto_now_add=True)),
                ('aceptado_rechazado_en', models.DateTimeField(blank=True, null=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='app.artista')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='app.evento')),
            ],
            options={
                'db_table': 'participacionevento',
            },
        ),
    ]
