# Generated by Django 4.2.16 on 2025-01-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='plan',
            field=models.CharField(choices=[('basico', 'Básico'), ('plan1', 'Plan 1'), ('plan2', 'Plan 2'), ('plan3', 'Plan 3'), ('admin', 'Admin')], default='basico', max_length=10),
        ),
    ]
