# Generated by Django 4.2.16 on 2025-01-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='verificacion',
            field=models.CharField(choices=[('EN_ESPERA', 'En Espera'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado')], default='EN_ESPERA', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='verificacion',
            field=models.CharField(choices=[('EN_ESPERA', 'En Espera'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado')], default='EN_ESPERA', max_length=20),
        ),
    ]
