# Generated by Django 4.2.16 on 2025-01-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_obra_verificacion_producto_verificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='acerca',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='artista',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='artista',
            name='imagen',
            field=models.ImageField(blank=True, default='artistas/avatar.png', null=True, upload_to='artistas/'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='ncontacto',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
